Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
#  config.vm.box = "ubuntu/bionic64"
#  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |vb|
     vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end
end
