version: '3.0'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: 'gitlab.example.com'
    ports:
      - '8080:80'
      - '8443:443'
      - '8022:22'
    environment:
     GITLAB_OMNIBUS_CONFIG: |
       external_url 'https://gitlab.example.com'
       # Add any other gitlab.rb configuration here, each on its own line
    networks:
      - gitlabnetwork
    volumes:
      - /Users/serge/Documents/projects/gitlab/config:/etc/gitlab
      - /Users/serge/Documents/projects/gitlab/logs:/var/log/gitlab
      - /Users/serge/Documents/projects/gitlab/data:/var/opt/gitlab

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    networks:
      - gitlabnetwork
    volumes:
      - runner:/etc/gitlab-runner

volumes:
  runner:

networks:
  gitlabnetwork:
